on:
  push:
      branches: [ "main" ]

name: ðŸš€ CNAD

jobs:

  web-deploy:
      name: ðŸŽ‰ Deploy
      runs-on: ubuntu-latest

      steps:
          - name: Clone repository
            uses: actions/checkout@v3

    # Important step, this is use to restart your server
          - name: Creating restart file
            run: |
              mkdir tmp && touch tmp/restart.txt 
              echo $RANDOM > tmp/restart.txt

    # Using FTP to upload your files to cpanel
          - name: ðŸ“‚ Sync files
            uses: SamKirkland/FTP-Deploy-Action@4.3.2
            with:
              server: 95.173.180.20
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
              server-dir: /ahmetselimboz.com.tr

              exclude: |
                  **/.github/**
                  **/.git/**
                  README.md
                  .gitignore
              